language: php

php:
  - 7.4

dist: focal

matrix:
  fast_finish: true

install:
  - composer install --prefer-dist --no-interaction

script:
  - |
    if [[ $TRAVIS_PHP_VERSION == '7.4' ]]; then
      export CODECOVERAGE=1 && vendor/bin/phpunit --verbose --coverage-clover=clover.xml
    else
      vendor/bin/phpunit
    fi
after_success:
  - |
    if [[ $TRAVIS_PHP_VERSION == '7.4' ]]; then
      wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.1.0/php-coveralls.phar
      chmod +x php-coveralls.phar
      ./php-coveralls.phar
    fi

notifications:
  email: false